Document: deemix
Title: Debian deemix Manual
Author: <insert document author here>
Abstract: This manual describes what deemix is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/deemix/deemix.sgml.gz

Format: postscript
Files: /usr/share/doc/deemix/deemix.ps.gz

Format: text
Files: /usr/share/doc/deemix/deemix.text.gz

Format: HTML
Index: /usr/share/doc/deemix/html/index.html
Files: /usr/share/doc/deemix/html/*.html
